# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-k8s-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world-k8s-api
  template:
    metadata:
      labels:
        app: hello-world-k8s-api
    spec:
      containers:
      - name: hello-world-k8s-api
        image: supermongol/hello-world-k8s-api
        ports:
        - containerPort: 8000